Client/package-lock.json
Client/package.json

Estoy instalando axios en client que faltaba....

instalacion de axios

---

Client/package-lock.json
Client/package.json

instalando redux toolkit

---

Api/src/db.js

me olvide de inicializarlo en el archivo db.js.

Initialize model Service_status

---

.github/workflows/notify.yml

edite el nombre el grupo de slack que estaba mal

editanto notify.yml

---

prueba.txt

archivo txt

---

Api/src/controllers/productController.js
Api/src/handlers/productHandlers.js

Reverts gabiMaglia/PF_HENRY#36

Revert "delete product, get prod by id, create prod, get all prod"

---

Api/src/controllers/productController.js
Api/src/controllers/serviceController.js
Api/src/handlers/ServiceHandlers.js
Api/src/handlers/productHandlers.js
Api/src/routes/mainRoutes.js
Api/src/routes/serviceRouter/serviceRouter.js

correccion de controllers y handlers ademas de conexion a rutas y peticiones funcionando. 
faltaria administrar el envio de datos, por eso no me eliminen la rama.

service controllers, handlers and routes done

---

Client/package-lock.json
Client/src/App.jsx
Client/src/components/Footer/Footer.components.jsx
Client/src/helpers/pathRoute.js
Client/src/main.jsx
Client/src/views/Products/Products.view.jsx
Client/src/views/Questions/Questions.view.jsx
Client/src/views/Support/Support.view.jsx

Rutas front

---

Client/src/App.jsx
Client/src/components/Footer/Footer.components.jsx

creando links de paginas en el footer

creando links de paginas en el footer

---

Client/src/components/NavBar/NavBar.component.jsx

cambio de color

---

Api/src/controllers/serviceController.js
Api/src/db.js
Api/src/handlers/ServiceHandlers.js
Endpoints.txt

gabi ahi lo corregi  lo de la tabla user ademas añadi que me ordene los datos al crear los servicios, me faltaria hacer una ruta get servicios solamente que la creo a la brevedad

arreglo de userID

---

Client/package-lock.json
Client/package.json
Client/src/components/Dropdown/Dropdown.component.jsx
Client/src/components/Support/Support.component.jsx
Client/src/utils/objectsTexts.js
Client/src/views/Support/Support.view.jsx

vista soporte y carpeta utils

---

Api/index.js
Api/src/controllers/userController.js
Api/src/handlers/userHandlers.js
Api/src/routes/userRouter/userRouter.js
Client/src/DataBase/bdd.json
Client/src/components/Home/Home.component.jsx
Client/src/components/HomeProduct/HomeProduct.component.jsx
Client/src/components/HomeProducts/HomeProducts.component.jsx
Client/src/hooks/useLocalStorage.jsx

Mejore tema estilos en los componentes y agregue mas datos a la base de datos de prueba

Componente HomeProducts. Home product. Agregado de datos en dataBase

---

Client/package-lock.json
Client/package.json
Client/src/App.jsx
Client/src/components/Carousel/Carousel.component.jsx
Client/src/components/ShoppingCart/ShoppingCart.component.jsx

ShoppingCart

---

Client/package-lock.json
Client/package.json
Client/src/components/Dropdown/Dropdown.component.jsx
Client/src/components/Support/Support.component.jsx
Client/src/helpers/supportValidateForm.js

validaciones del formulario de soporte

validaciones del formulario de soporte

---

Client/src/App.jsx
Client/src/DataBase/bdd.json
Client/src/components/Detail/Detail.component.jsx
Client/src/components/Home/Home.component.jsx
Client/src/components/HomeProduct/HomeProduct.component.jsx
Client/src/components/HomeProducts/HomeProducts.component.jsx
Client/src/views/Detail/Detail.view.jsx

Agregue componente Detail View y Detail component

Nuevo detail

---

Client/src/components/Support/Support.component.jsx

posicionamiento del formulario pagina soporte

posicionamiento del formulario pagina soporte

---

Api/src/db.js

modificacion de variables de entorno y conexion a DB

modificacion de variables de entorno y conexion a DB

---

Client/src/components/CarouselTop/CarouselTop.component.jsx
Client/src/components/Home/Home.component.jsx

modificando el alto del carosuel para que encaje bien la imagen

modificando el alto del carosuel

---

Api/src/controllers/serviceControllers/serviceController.js
Api/src/handlers/ServiceHandlers.js

modificacion de los error handlers para que no sea throw new errors.

Error handlers

---

Api/src/db.js

ayudando a mariangel

---

Api/package.json
Api/src/config/mailer.js
Api/src/controllers/serviceControllers/serviceController.js
Api/src/routes/mainRoutes.js

Nodemailer

---

Client/src/services/ProductServices.js

listo service

---

Client/src/utils/objectsTexts.js

cambio correo electronico

---

Api/src/controllers/mailingController.js

agregando userEmail al cuerpo del mensaje

agregando userEmail al cuerpo del mensaje

---

Api/src/controllers/mailingController.js
Api/src/handlers/mailingHandler.js
Client/src/components/Support/Support.component.jsx

formulario soporte

---

Client/src/components/Detail/Detail.component.jsx
Client/src/components/ProductsBox/ProductsBox.componets.jsx
Client/src/components/SearchBar/SearchBar.component.jsx

Comprobando el funcionamiento del agregado de productos al carrito.

Agregando productos al carrito

---

Api/index.js
Api/src/controllers/serviceControllers/serviceController.js
Api/src/handlers/serviceHandlers/ServiceHandlers.js
Api/src/routes/serviceRouter/serviceRouter.js

añadi una funcion para traer por cliente la cantidad de servicios que tiene

add getByClientID

---

Client/src/components/LoginModal/LoginModal.component.jsx
Client/src/components/SearchBar/SearchBar.component.jsx

Solución de error de tipografía en una variable

Solución de error LoginModal

---

Api/src/controllers/serviceControllers/serviceController.js
Api/src/handlers/serviceHandlers/ServiceHandlers.js

añadi la funcion de traer por el modelo. busca tanto por nombre completo o por una parte del modelo. ademas modifique la estructura del mail de ingreso y añadi el mail de actualizacion de estados.

Service details

---

Client/src/components/Support/Support.component.jsx

Creando un estado local para la solicitud POST para el envió del formulario.

formulario en estado local

---

Client/src/components/LoginModal/LoginModal.component.jsx

Se agrego un botón para cerrar el Modal de inicio de sesión

Close button login modal

---

Client/src/components/Support/Support.component.jsx

Desactivando el botón de enviar hasta que no se completen todos los campos.  Spinner de carga en el botón hasta que se envíe el mensaje.

disabled al boton y spinner de carga

---

Client/src/redux/slices/ProducSlice.js

No de nuevo

---

Client/src/components/Categories/Categories.component.jsx
Client/src/redux/slices/ProducSlice.js

Orden precio

---

Client/src/components/Dropdown/Dropdown.component.jsx
Client/src/utils/objectsTexts.js

link whatsapp preguntas frecuentes

link wahtsapp

---

Client/src/components/Categories/Categories.component.jsx
Client/src/components/Products/Products.componet.jsx
Client/src/redux/slices/ProducSlice.js

filtrados categorias

---

Client/src/components/Categories/Categories.component.jsx
Client/src/redux/slices/ProducSlice.js

Cambios peq

---

Client/src/components/LoginModal/LoginModal.component.jsx
Client/src/components/RegisterModal/RegisterModal.component.jsx
Client/src/helpers/userValidate.js

Corrección de errores y modificación de envió de parámetros

Correccion registe modal

---

Client/src/components/Categories/Categories.component.jsx
Client/src/components/Products/Products.component.jsx
Client/src/redux/slices/ProductSlice.js

eliminando console.log

---

Client/src/components/LoginModal/LoginModal.component.jsx
Client/src/components/RegisterModal/RegisterModal.component.jsx

Se crearon los mensajes y redireccionamiento para el momento de registrarse o iniciar sesion

Mensajes registro e inicio sesion

---

Client/src/components/Detail/Detail.component.jsx

El q lo acepte borre la rama y haga el merge. Graciass

Responsive del Detail

---

Client/.env
Client/src/components/Categories/Categories.component.jsx
Client/src/components/Products/Products.component.jsx
Client/src/redux/slices/ProductSlice.js
Client/src/utils/objectsTexts.js

filtrados categoria y marca

---

Client/src/components/Categories/Categories.component.jsx
Client/src/redux/slices/ProductSlice.js

reseteo de estados y filtros al dar click en el boton Limpiar

reseteado de filtrados y estados

---

Client/src/components/Support/Support.component.jsx

Página de soporte responsive para tablet y mobile.

pagina de soporte resnponsive

---

Client/src/components/Dropdown/Dropdown.component.jsx

responsive de la pagina preguntas frecuentes para tablet y mobile

responsive de la pagina preguntas frecuentes

---

Client/src/helpers/userValidate.js

Cambio en el regex para la validación del numero de teléfono en el registro de usuario

Arreglo en verificación del numero de telefono Registro

---

Client/src/components/Categories/Categories.component.jsx

cambios estilos

---

Client/src/components/Categories/Categories.component.jsx
Client/src/components/Products/Products.component.jsx
Client/src/components/ProductsBox/ProductsBox.component.jsx

cambios en el estilo

---

Api/index.js
Client/src/Hook/useLocalStorage.jsx
Client/src/components/LoginModal/LoginModal.component.jsx
Client/src/components/RegisterModal/RegisterModal.component.jsx
Client/src/components/SearchBar/SearchBar.component.jsx
Client/src/services/AuthServices.js

Renderizados condicionales con sesiones

Inicio de sesion

---

Client/src/services/AuthServices.js
Client/src/services/ProductServices.js
Client/src/services/ServiceServices.js
Client/src/services/UserServices.js

Se cambiaron las importaciones de las variables de entorno en las funciones Services

Cambio en las variables de entorno

---

Api/src/controllers/serviceControllers/serviceController.js
Api/src/handlers/serviceHandlers/ServiceHandlers.js
Api/src/routes/serviceRouter/serviceRouter.js

añadi una funcion para filtrar por status, ademas de algunos banners al enviar mails, a los mismos le falta amor pero estan presentes.

Fix service

---

Client/src/DataBase/categories.json

correcciones

---

Client/src/DataBase/categories.json
Client/src/components/Categories/Categories.component.jsx
Client/src/components/Detail/Detail.component.jsx
Client/src/components/Home/Home.component.jsx
Client/src/components/HomeProducts/HomeProducts.component.jsx
Client/src/components/ProductCard/ProductCard.component.jsx
Client/src/components/Products/Products.component.jsx
Client/src/components/ProductsBox/ProductsBox.component.jsx
Client/src/components/SearchBar/SearchBar.component.jsx
Client/src/redux/slices/ProductSlice.js
Client/src/services/ProductServices.js

Redux funcionando

---

Client/src/redux/slices/ProductSlice.js

cambio de estado olvidado

---

Client/src/DataBase/bdd.json
Client/src/redux/slices/CartSlice.js

Creando el slice component del carrito

Cart slice

---

Client/package-lock.json
Client/package.json
Client/src/App.jsx

Implementación de reCaptcha V3 de Google

re captcha

---

Client/src/redux/slices/CartSlice.js

Probando el Slice

---

Client/package-lock.json
Client/package.json
Client/src/components/LoginModal/LoginModal.component.jsx
Client/src/components/Products/Products.component.jsx
Client/src/components/RegisterModal/RegisterModal.component.jsx
Client/src/components/SearchBar/SearchBar.component.jsx
Client/src/services/AuthServices.js
Client/src/utils/cookiesFunctions.js

Lógica y funcionalidad para el almacenamiento de los datos de autenticación de usuario en cookies

Implementación de cookies

---

Client/src/App.jsx
Client/src/components/LoginModal/LoginModal.component.jsx
Client/src/components/RegisterModal/RegisterModal.component.jsx
Client/src/components/SearchBar/SearchBar.component.jsx
Client/src/components/Support/Support.component.jsx

Modificando el captcha para que solo se active en los formularios de inicio se sesión, registro y soporte.

re captcha v3 solo para formularios

---

Client/src/components/CarouselTop/CarouselTop.component.jsx

Editando pequeño delay al hacer click en la imagen del carousel y redirigir al detalle del mismo con useNavigate

editanto delay al redirigir

---

Client/src/components/WhatsApp/WhatsApp.component.jsx

boton de whatsapp

---

Client/src/components/LoginModal/LoginModal.component.jsx
Client/src/utils/cookiesFunctions.js

Solución de error en inicio de sesión incorrecto

Solucion de errores cookies

---

Client/src/components/ShoppingCart/ShoppingCart.component.jsx

Componente listo

---

Client/src/App.jsx
Client/src/components/ButtonScrollTop/ButtonScrollTop.component.jsx
Client/src/components/Home/Home.component.jsx

boton scroll al inicio

---

Client/src/App.jsx
Client/src/components/ButtonScrollTop/ButtonScrollTop.component.jsx
Client/src/components/Home/Home.component.jsx
Client/src/components/WhatsApp/WhatsApp.component.jsx

poniendo boton de whatsapp en toda la app

poniendo boton de whatsapp en toda la app

---

Client/src/components/ProductsBox/ProductsBox.component.jsx
Client/src/components/ShoppingCart/ShoppingCart.component.jsx
Client/src/redux/slices/CartSlice.js

Funcionalidad lista

---

Client/src/App.jsx
Client/src/components/Detail/Detail.component.jsx
Client/src/components/ProductsBox/ProductsBox.component.jsx
Client/src/components/ShoppingCart/ShoppingCart.component.jsx
Client/src/helpers/pathRoute.js
Client/src/redux/slices/CartSlice.js

Shopping cart

---

Client/src/components/ButtonScrollTop/ButtonScrollTop.component.jsx
Client/src/components/CarouselTop/CarouselTop.component.jsx
Client/src/components/WhatsApp/WhatsApp.component.jsx

editando detalles de botones, cursor pointer carousel

editando detalles

---

Client/src/components/HomeProducts/HomeProducts.component.jsx

Centrado de HomeProducts

---

Client/src/components/CarouselBottom/CarouselBottom.component.jsx
Client/src/components/GoogleMap/GoogleMap.component.jsx
Client/src/components/HomeProducts/HomeProducts.component.jsx
Client/src/components/ProductCard/ProductCard.component.jsx
Client/src/main.jsx
Client/src/redux/slices/CategoriesSlice.js
Client/src/redux/slices/ProductSlice.js
Client/src/redux/store.js
Client/src/services/CategoriesServices.js
Client/src/services/ProductServices.js

migas de pan

---

Client/src/App.jsx
Client/src/components/HomeProducts/HomeProducts.component.jsx
Client/src/components/ProductCard/ProductCard.component.jsx
Client/src/components/ProductsBox/ProductsBox.component.jsx
Client/src/components/Support/Support.component.jsx
Client/src/helpers/pathRoute.js
Client/src/redux/slices/ProductSlice.js
Client/src/views/Categories/Categories.view.jsx

Ruta para mostrar todos los productos de una categoría al hacer click en la miga de pan de la Card

Ruta categorias

---

Client/src/components/SearchBar/SearchBar.component.jsx

Corazon de favoritos en las Card

trabajnado en favoritos

---

Client/src/Hook/useLocalStorage.jsx
Client/src/components/ProductsBox/ProductsBox.component.jsx
Client/src/components/ShoppingCart/ShoppingCart.component.jsx
Client/src/redux/slices/CartSlice.js

cambios logica

---

Client/src/components/SearchBar/SearchBar.component.jsx

Sumatoria de productos en el Icono del carrito (SearchBar)

Agregando estilo

---

Client/src/Hook/useLocalStorage.jsx
Client/src/components/ShoppingCart/ShoppingCart.component.jsx

CREO QUE AHORA SI

---

Client/src/components/CarouselProducts/CarouselProducts.component.jsx
Client/src/components/Detail/Detail.component.jsx
Client/src/components/HomeProducts/HomeProducts.component.jsx

Creacion de   carousel Products y random a lahora de traer productos

Carousel products

---

Client/src/Hook/useLocalStorage.jsx
Client/src/components/ShoppingCart/ShoppingCart.component.jsx
Client/src/redux/slices/CartSlice.js

Va queriendo

---

Client/src/components/Detail/Detail.component.jsx

Trabajando en la fusion del detail con el logo del carrito

Detail logo

---

Api/src/controllers/userControllers/userController.js
Client/src/App.jsx
Client/src/components/utils/ProtectedRoutes/ProtectedRoutes.component.jsx
Client/src/components/utils/SessionAlert/SessionAlert.component.jsx
Client/src/redux/slices/ProductSlice.js
Client/src/services/AuthServices.js

Protegiendo rutas según sesión y rol de usuario

Rutas protegidas cookies

---

Client/src/App.jsx
Client/src/components/Categories/Categories.component.jsx
Client/src/components/Home/Home.component.jsx
Client/src/redux/slices/ProductSlice.js
Client/src/services/ProductServices.js

vuelta atras

---

Client/src/components/CarouselProducts/CarouselProducts.component.jsx
Client/src/components/Detail/Detail.component.jsx

arreglo de error por consola en carouselProducts

arreglo de error por consola en carouselProducts

---

Api/index.js
Client/src/components/ProductCard/ProductCard.component.jsx
Client/src/components/ProductsCategories/ProductsCategories.component.jsx

Favorites2

---

Api/src/handlers/productHandlers/wishListHandlers.js
Client/src/components/ProductCard/ProductCard.component.jsx
Client/src/redux/slices/WishListSlice.js
Client/src/redux/store.js
Client/src/services/WishListServices.js

icono de wishlist funcional en el front. faltan limar detalles varios, pero funciona

Wishlist front

---

Client/src/components/ShoppingCart/ShoppingCart.component.jsx
Client/src/redux/slices/CartSlice.js
Client/src/services/ProductServices.js

mercadopago

---

Client/src/components/RegisterModal/RegisterModal.component.jsx

Se elimino la posibilidad de iniciar sesión luego de registrarse.

Arreglo registro

---

Client/src/components/ProductsServicesProfile/ProductServicesProfile.component.jsx
Client/src/components/ShoppingProfile/ShoppingProfile.component.jsx
Client/src/components/SideBar/SideBar.component.jsx
Client/src/components/WishListProfile/WishListProfile.component.jsx
Client/src/views/privates/UserProfile/UserProfile.view.jsx

Cambio de color en el boton del sideBar que se encuentra actualmente el usuario

Arreglos en edit

---

Client/src/components/Detail/Detail.component.jsx
Client/src/components/ProductsBox/ProductsBox.component.jsx
Client/src/redux/slices/CartSlice.js

Funcionalidad lista en la fusion ProductBox <---> ShoppingCart

Funcionalidad terminada

---

Client/src/components/ProductsServicesProfile/ProductServicesProfile.component.jsx
Client/src/components/ShoppingProfile/ShoppingProfile.component.jsx
Client/src/components/SideBar/SideBar.component.jsx
Client/src/components/WishListProfile/WishListProfile.component.jsx
Client/src/views/privates/UserProfile/UserProfile.view.jsx

Se implemento un slider en el panel de usuario para recorrer entre las distintas vistas del mismo

Slider en panel de usuario

---

Client/src/components/SideBar/SideBar.component.jsx
Client/src/components/UserMenu/UserMenu.component.jsx

Solución del error al cerrar sesión desde el sidebar

Arreglo en logout de sidebar

---

Client/src/App.jsx
Client/src/components/SideBar/SideBar.component.jsx
Client/src/services/AuthServices.js

Solución de errores en los redireccionamientos

Arreglo de errores

---

Client/src/components/UserMenu/UserMenu.component.jsx

Se transformo el userMenu para que sea dinamico y renderize los items que contiene un array

UserMenu dinamico terminado

---

Client/src/components/EcommerceCard/EcommerceCard.component.jsx

actualizando

---

Client/src/components/EcommerceCard/EcommerceCard.component.jsx

Pequeño cambio

---

Client/src/components/UserPanel/UserPanel.component.jsx
Client/src/components/utils/ProtectedRoutes/ProtectedRoutes.component.jsx

formaro codigo

---

Client/src/components/GoogleMap/GoogleMap.component.jsx

tamaño mapa

---

Client/src/components/SideBar/SideBar.component.jsx
Client/src/components/UserMenu/UserMenu.component.jsx
Client/src/helpers/pathRoute.js
Client/src/utils/sidebarItems.jsx

User Menu para role de tecnico

user menu tecnicos

---

Client/src/components/EcommerceCard/EcommerceCard.component.jsx

Agregando la fecha actual al panel de productos

CurrentDate

---

Client/src/App.jsx
Client/src/components/UserMenu/UserMenu.component.jsx
Client/src/components/UserPanel/UserPanel.component.jsx
Client/src/helpers/pathRoute.js
Client/src/utils/sidebarItems.jsx

rutas protegidas

---

Client/src/components/CarouselBottom/CarouselBottom.component.jsx
Client/src/components/SearchBar/SearchBar.component.jsx
Client/src/index.css

correccion borde

---

Client/src/components/CarouselTop/CarouselTop.component.jsx
Client/src/components/Footer/Footer.component.jsx
Client/src/components/HomeProducts/HomeProducts.component.jsx
Client/src/index.css

responsive

---

Client/src/components/Support/Support.component.jsx

agregando atributos

---

Client/src/components/ProductsServicesCustomer/ProductsServicesCustomer.component.jsx

Correccion de error

---

Client/src/components/ProductsServicesCustomer/ProductsServicesCustomer.component.jsx

Actualizado

---

Client/src/components/ProductsServicesProfile/ProductServicesProfile.component.jsx
Client/src/components/ShoppingProfile/ShoppingProfile.component.jsx
Client/src/components/UserProfileProductCard/UserProfileProductCard.component.jsx
Client/src/components/WishListProfile/WishListProfile.component.jsx

Cambio de nombres en archivos del panel de usuario

Nombres en archivos

---

Client/src/components/UserProfileProductCard/UserProfileProductCard.component.jsx
Client/src/components/WishListProfile/WishListProfile.component.jsx

Renderizado de los productos reales traídos desde el back en la vista Lista de Deseados, y funcionalidad a los botones.

Wishlist desde back

---

Client/src/components/UserProfile/UserProfile.component.jsx
Client/src/components/UserProfileProductCard/UserProfileProductCard.component.jsx
Client/src/components/WishListProfile/WishListProfile.component.jsx

Se agrego el redireccionamiento al detalle del producto desde las cards de la Wishlist y se ordeno un poco el codigo agregando comentarios

Detail product desde card

---

Client/src/components/EditModal/EditModal.jsx
Client/src/components/LoginModal/LoginModal.component.jsx
Client/src/components/RegisterModal/RegisterModal.component.jsx
Client/src/components/SearchBar/SearchBar.component.jsx
Client/src/components/SideBar/SideBar.component.jsx
Client/src/components/UserMenu/UserMenu.component.jsx
Client/src/index.css

Arreglo de estilos en modales de formularios y el menú de usuario desplegable

Arreglo de estilos

---

Client/src/components/Dropdown/Dropdown.component.jsx
Client/src/components/ProductsBox/ProductsBox.component.jsx
Client/src/components/Support/Support.component.jsx

arreglando estilos mobile

---

Client/src/components/ProductsServicesProfile/ProductServicesProfile.component.jsx
Client/src/components/ShoppingProfile/ShoppingProfile.component.jsx
Client/src/components/SideBar/SideBar.component.jsx
Client/src/components/UserPanel/UserPanel.component.jsx
Client/src/components/UserPanelProductCard/UserPanelProductCard.component.jsx
Client/src/components/UserProfile/UserProfile.component.jsx
Client/src/components/UserProfileProductCard/UserProfileProductCard.component.jsx
Client/src/components/WishListProfile/WishListProfile.component.jsx

Se mejoraron los estilos generales userPanel

Estilos generales user panel

---

Client/src/helpers/pathRoute.js
Client/src/utils/UserPanelItems.jsx

arreglando rutas

---

Client/src/helpers/pathRoute.js
Client/src/utils/UserPanelItems.jsx

ruta de usuarios

---

Client/src/components/ProductCreateProfile/ProductCreateProfile.component.jsx

modificacion en el input de imagen. ahora deja seleccionar muchas de una sola vez

seleccion multiple de archivos

---

Api/src/controllers/productControllers/productController.js
Client/src/utils/objectsTexts.js

Cloudinary2

---

Client/src/components/CreateService/CreateService.component.jsx
Client/src/components/UserPanel/UserPanel.component.jsx
Client/src/utils/UserPanelItems.jsx

Adaptación de la vista creación de servicios para el Admin

Creación de servicios admin

---

Client/src/components/CreateService/CreateService.component.jsx
Client/src/helpers/serviceValidate.js
Client/src/services/userServices.js

Creación de validaciones para el formulario de creación de servicio

validaciones formulario creación de servicio

---

Api/src/controllers/serviceControllers/serviceController.js
Client/src/components/CreateService/CreateService.component.jsx
Client/src/components/ImageUploader.jsx
Client/src/helpers/serviceValidate.js
Client/src/services/authServices.js
Client/src/services/serviceServices.js
Client/src/utils/cloudinaryUpload.js

Formulario de creación de servicio terminado.

Creación de servicio

---

Client/src/components/CreateService/CreateService.component.jsx
Client/src/components/LoginModal/LoginModal.component.jsx
Client/src/components/ProductsServicesProfile/ProductServicesProfile.component.jsx
Client/src/services/serviceServices.js

Cambio en la forma de traer el token de sesión en el formulario de creación de servicio y arreglo en la alerta cuando habia un login incorrecto

Arrreglo jwt create service

---

Client/src/components/utils/ProtectedRoutes/ProtectedRoutes.component.jsx

Arreglo de error en verificación de sesión al momento de recargar la pagina.

Arreglo en permisos cuando se recarga

---

Api/src/controllers/productControllers/productController.js
Api/src/handlers/productHandlers/productHandlers.js
Api/src/routes/productRouter/productRouter.js

Se creo una ruta para crear productos de forma masiva y no tener que pasar de a uno.

Creación de productos masivo

---

Api/src/controllers/serviceControllers/serviceController.js
Client/src/components/ProductsServicesProfile/ProductServicesProfile.component.jsx
Client/src/services/serviceServices.js

Arreglo de errores en la obtención de serviciós

Producos en servicio reales

---

Client/src/components/CreateService/CreateService.component.jsx
Client/src/helpers/serviceValidate.js
Client/src/utils/cloudinaryUpload.js

Productos en servicio reales

---

Api/src/controllers/productControllers/productController.js
Client/src/components/UserPanel/UserPanel.component.jsx

Corrección ruta userList en navegación de panel de usuario de Admin

User panel

---

Client/src/components/ProductsServicesProfile/ProductServicesProfile.component.jsx
Client/src/components/WishListProfile/WishListProfile.component.jsx

Modularización de componente Wishlist.

Modularización de wishlist profile

---

Client/src/components/ProductsServicesProfile/ProductServicesProfile.component.jsx
Client/src/components/WishListProfile/WishListProfile.component.jsx

Arreglos visuales en productos en servicio y en la lista de deseos.

Arreglos visuales

---

Client/src/components/CardCarousel/CardCarousel.component.jsx

Box shadow a imagen del producto

box shadow image

---

Client/src/components/ProductCreateProfile/ProductCreateProfile.component.jsx
Client/src/helpers/productValidate.js

añadi validaciones en todos los campos, faltan muchos estilos. 
pd:mirenlo funcionando acepto criticas y ayudas obviamente

Form creates

---

Client/src/components/UsersTable/UsersTable.component.jsx
Client/src/helpers/getFirstLetters.js
Client/src/services/userServices.js

Arreglo en obtención de nombre y apellido

Arreglo en error de user menu

---

Client/src/components/DetailProductService/DetailProductService.component.jsx

Renderizado de datos desde el back

Renderizado

---

Client/src/components/ProductsTable/ProductsTable.component.jsx
Client/src/components/UserPanel/UserPanel.component.jsx
Client/src/components/UsersTable/UsersTable.component.jsx
Client/src/components/utils/ProtectedRoutes/ProtectedRoutes.component.jsx
Client/src/helpers/pathRoute.js
Client/src/services/userServices.js
Client/src/utils/UserPanelItems.jsx

Algunos cambios

---

Api/src/controllers/serviceControllers/serviceController.js
Api/src/handlers/serviceHandlers/ServiceHandlers.js
Api/src/routes/serviceRouter/serviceRouter.js
Client/src/components/ProductsServicesProfile/ProductServicesProfile.component.jsx
Client/src/components/UsersTable/UsersTable.component.jsx
Client/src/services/serviceServices.js

Se agrego un filtrado de servicios en la vista de productos en servicio.

Filtrado de servicios

---

Client/src/components/UserPanelProductCard/UserPanelProductCard.component.jsx
Client/src/components/UsersTable/UsersTable.component.jsx
Client/src/components/WishListProfile/WishListProfile.component.jsx

Se arreglo el agregar al carrito de la WishList

Arreglo en agregar al carrito WishList

---

Client/src/components/Loading/Loading.component.jsx

editando loading

---

Client/src/components/ProductsBox/ProductsBox.component.jsx
Client/src/components/WishListProfile/WishListProfile.component.jsx

ScrollToTop

---

Client/src/components/DetailProductService/DetailProductService.component.jsx
Client/src/components/ProductsServicesProfile/ProductServicesProfile.component.jsx
Client/src/services/userServices.js

Detalles estéticos en product service detail.

Arreglo product service

---

Client/src/components/ShoppingProfile/ShoppingProfile.component.jsx
Client/src/services/categoriesServices.js
Client/src/services/serviceServices.js
Client/src/services/userServices.js
Client/src/services/wishListServices.js

Se agregaron alertas a botones sin funcionalidad.

Alerta en botones no funcionales

---

Client/src/components/UsersTable/UsersTable.component.jsx

Traducción de lista de usuarios

Traducción

---

Client/src/components/CustomToolbar/CustomToolbar.component.jsx
Client/src/components/ProductsTable/ProductsTable.component.jsx

Products table

---

Api/src/controllers/productControllers/productController.js
Api/src/handlers/productHandlers/productHandlers.js
Api/src/routes/productRouter/productRouter.js
Client/src/components/ProductsTable/ProductsTable.component.jsx
Client/src/services/productServices.js

Se agrego una ruta, un handler y un controller en el back para manejar el borrado lógico de productos.

Borrado logico de productos en el back

---

Client/src/components/ProductsTable/ProductsTable.component.jsx
Client/src/components/WhatsApp/WhatsApp.component.jsx

Tabla productos

---

Client/src/components/ProductCreateProfile/ProductCreateProfile.component.jsx

añadi alertas

---

Api/src/controllers/productControllers/productController.js
Api/src/handlers/productHandlers/productHandlers.js

Cambio en la funcionalidad de el put de productos.

Arreglo put use

---

Client/src/components/DropdownService/DropdownService.component.jsx
Client/src/components/DropdownStore/DropdownStore.component.jsx
Client/src/components/Questions/Questions.component.jsx
Client/src/utils/objectsTexts.js
Client/src/views/publics/Questions/Questions.view.jsx

actualización de preguntas frecuentes

actualización de preguntas frecuentes

---

Client/src/components/ProductsTable/ProductsTable.component.jsx
Client/src/services/productServices.js

Lista productos

---

Client/src/components/ServiceList/ServiceList.componet.jsx
Client/src/components/UserPanel/UserPanel.component.jsx
Client/src/helpers/pathRoute.js
Client/src/utils/UserPanelItems.jsx

Service list

---

Api/index.js
Api/src/controllers/pagosControllers/mercadoPagoContoller.js
Api/src/controllers/pagosControllers/ordersControllers.js
Api/src/controllers/productControllers/cartControllers.js
Api/src/controllers/serviceControllers/serviceController.js
Api/src/handlers/pagosHandlers/mercadoPagoHandler.js
Api/src/models/ServiceModels/Service_status.js
Client/src/components/DetailProductService/DetailProductService.component.jsx
Client/src/components/ShoppingCart/ShoppingCart.component.jsx
Client/src/components/UsersTable/UsersTable.component.jsx
Client/src/services/productServices.js

Carrousel de compras y pasos de servicio

Pasos de reparación

---

Client/src/components/Review/Review.component.jsx

redireccion y agregado de comentarios.

redireccion y comentario

---

Api/src/controllers/pagosControllers/mercadoPagoContoller.js
Api/src/controllers/pagosControllers/ordersControllers.js
Api/src/handlers/pagosHandlers/orderHandlers.js
Api/src/routes/mainRoutes.js
Api/src/routes/pagosRouter/pagosRouter.js

Se arreglo un error en las compras, cuando se compraban varias productos iguales disminuía el stock solo en 1.

Arreglo en compras

---

Client/src/components/ProductCard/ProductCard.component.jsx

formateo precio

---

Client/src/components/CreateService/CreateService.component.jsx
Client/src/components/ProductCreateProfile/ProductCreateProfile.component.jsx
Client/src/components/ProductsServicesProfile/ProductServicesProfile.component.jsx
Client/src/components/UserPanel/UserPanel.component.jsx
Client/src/helpers/pathRoute.js
Client/src/utils/UserPanelItems.jsx

acomodando navegación de paneles de usuarios según los roles

Service list panel

---

Client/src/helpers/pathRoute.js

cambio nombre ruta lista de servicios

cambio nombre ruta lista de servicios

---

Client/src/components/DetailProductService/DetailProductService.component.jsx

Estilado del componente ProductServiceDetail

Pasos de reparacion

---

Api/src/controllers/productControllers/cartControllers.js
Api/src/handlers/productHandlers/cartHandlers.js

Reverts gabiMaglia/PF_HENRY#485

Revert "Cart total"

---

Client/src/components/Review/Review.component.jsx

Comentario

---

Api/src/controllers/productControllers/productController.js
Api/src/handlers/productHandlers/productHandlers.js
Client/src/components/ProductsTable/ProductsTable.component.jsx
Client/src/services/productServices.js

Lista de productos

---

Api/src/controllers/productControllers/productController.js
Client/src/components/ProductsTable/ProductsTable.component.jsx
Client/src/components/WhatsApp/WhatsApp.component.jsx
Client/src/services/productServices.js

Productos lista

---

Client/src/components/Categories/Categories.component.jsx
Client/src/redux/slices/brandsSlice.js
Client/src/redux/store.js
Client/src/services/brandsServices.js

obtención de las marcas desde la DB y ordenamiento en el select

Marcas db new

---

Api/src/controllers/pagosControllers/mercadoPagoContoller.js
Client/src/components/Detail/Detail.component.jsx
Client/src/components/ShoppingProfile/ShoppingProfile.component.jsx
Client/src/components/WishListProfile/WishListProfile.component.jsx

Se agrego una alerta al volver a la pagina después de haber comprado un producto.

Correcciones varias

---

Api/src/controllers/serviceControllers/serviceController.js

modificando cuerpo del mensaje

modificando cuerpo del mensaje

---

Api/src/controllers/serviceControllers/serviceController.js
Api/src/controllers/userControllers/userController.js
Api/src/handlers/userHandlers/userHandlers.js
Api/src/models/ServiceModels/Service.js
Api/src/models/userModels/User.js
Client/src/components/DetailProductService/DetailProductService.component.jsx
Client/src/components/ProductsServicesProfile/ProductServicesProfile.component.jsx
Client/src/services/userServices.js

Elección de preferencia de comunicación

Estados de servicio

---

Client/src/components/ProductCreateProfile/ProductCreateProfile.component.jsx

ordenar marcas alfabeticamente en el select

ordenar marcas alfabeticamente en el select

---

Client/src/components/UserMenu/UserMenu.component.jsx
Client/src/redux/slices/cartSlice.js

correcion carrito

---

Api/src/controllers/serviceControllers/serviceController.js
Client/src/components/Detail/Detail.component.jsx
Client/src/components/SearchBar/SearchBar.component.jsx

correccion

---

Client/src/components/Detail/Detail.component.jsx
Client/src/components/WishListProfile/WishListProfile.component.jsx

Arreglos varios

---

Api/package-lock.json
Api/package.json
Api/src/controllers/productControllers/productController.js
Api/src/handlers/productHandlers/productHandlers.js
Client/src/components/ProductCard/ProductCard.component.jsx
Client/src/components/SearchBar/SearchBar.component.jsx

Input search bar

---

Api/src/controllers/googleControllers/googleReviewsController.js
Api/src/controllers/productControllers/categoryController.js
Api/src/handlers/googleHandlers/googleReviewsHandlers.js
Api/src/routes/googleRouter/googleReviewsRouter.js
Api/src/routes/mainRoutes.js

google reviews

---

Api/index.js
Api/src/controllers/productControllers/productController.js
Api/src/handlers/productHandlers/productHandlers.js
Api/src/models/productModels/Product.js
Client/src/components/CardCarousel/CardCarousel.component.jsx
Client/src/components/ProductCreateProfile/ProductCreateProfile.component.jsx

Carousel edit

---

Api/index.js
Client/src/components/CustomDataGrid/CustomDataGrid.component.jsx
Client/src/components/ProductsTable/ProductsTable.component.jsx

Carousel tabla prodcutos

---

Client/src/components/CardCarousel/CardCarousel.component.jsx

width imagen carousel

---

Client/src/components/UserPanelProductCard/UserPanelProductCard.component.jsx

cambios-correccion

---

Api/src/controllers/serviceControllers/serviceController.js
Client/src/components/ServicesTable/ServicesTable.component.jsx

datos usuario y tecnico servicios

datos usuario y tecnico servicios

---

Client/src/components/Reviews/Reviews.component.jsx

aplicando estilos

---

Api/src/controllers/pagosControllers/mercadoPagoContoller.js
Api/src/controllers/pagosControllers/ordersControllers.js
Api/src/models/productModels/Order.js
Api/src/routes/mainRoutes.js
Api/src/routes/pagosRouter/pagosRouter.js
Client/src/components/Home/Home.component.jsx
Client/src/components/ShoppingCart/ShoppingCart.component.jsx
Client/src/components/ShoppingProfile/ShoppingProfile.component.jsx
Client/src/services/reportingAnalyticsServices.js

Añadiendo datos que devuelve el webhook de mercado pago

Mercado pago

---

Api/src/middlewares/jwtSession.js
Client/src/components/Home/Home.component.jsx
Client/src/components/ProductsServicesProfile/ProductServicesProfile.component.jsx
Client/src/components/ToolbarServiceProfile/ToolbarServiceProfile.component.jsx
Client/src/components/UserProfile/UserProfile.component.jsx
Client/src/redux/slices/userSlice.js

Configuración para la elección de preferencia de comunicación, y renderizado de la misma en el perfil del usuario

Ajuste preferencia de comunicación

---

Api/src/controllers/productControllers/productController.js
Client/src/components/Products/Products.component.jsx

busqueda por categorias serachBar

busqueda por categorias serachBar

---

Api/src/controllers/serviceControllers/serviceController.js
Api/src/handlers/serviceHandlers/ServiceHandlers.js
Client/src/components/ServicesTable/ServicesTable.component.jsx
Client/src/services/serviceServices.js

manejo errores getAllServices

---

Api/index.js
Api/src/controllers/productControllers/productController.js
Api/src/controllers/serviceControllers/serviceController.js
Api/src/handlers/serviceHandlers/ServiceHandlers.js
Api/src/routes/serviceRouter/serviceRouter.js

Borrado logico

---

Client/src/components/ServicesTable/ServicesTable.component.jsx
Client/src/services/productServices.js
Client/src/services/serviceServices.js

borrado logico front services

---

Client/src/components/ServicesTable/ServicesTable.component.jsx

Services table

---

Client/src/components/Home/Home.component.jsx
Client/src/utils/objectsTexts.js

enlaces en preguntas frecuentes

enlaces en preguntas frecuentes

---

Client/src/components/ProductsServicesProfile/ProductServicesProfile.component.jsx
Client/src/components/ShoppingProfile/ShoppingProfile.component.jsx
Client/src/components/UserPanelProductCard/UserPanelProductCard.component.jsx
Client/src/services/firebaseAnayticsServices.js

Adición de eventos en las compras

Eventos analytics

---

Api/src/controllers/serviceControllers/serviceController.js
Api/src/handlers/serviceHandlers/ServiceHandlers.js
Client/src/components/CreateService/CreateService.component.jsx
Client/src/components/SearchBar/SearchBar.component.jsx
Client/src/components/ServicesTable/ServicesTable.component.jsx
Client/src/components/UserMenu/UserMenu.component.jsx
Client/src/services/serviceServices.js

Se modifico la forma en que se cambia del técnico de un servicio.

Cambio de tecnico servicio

---

Client/src/components/Detail/Detail.component.jsx

correccion error al hacer click en carousel sin sesion iniciada

correccion error al hacer click en carousel sin sesion iniciada

---

Client/src/components/CardCarousel/CardCarousel.component.jsx
Client/src/components/Notifications/Notifications.component.jsx

tamaño icono notificacion

---

Client/src/components/UserMenu/UserMenu.component.jsx

Me quedo un cambio sin guardar antes de hacer el push.

Overflow scroll

---

Api/src/controllers/productControllers/productController.js
Api/src/handlers/productHandlers/productHandlers.js
Api/src/routes/productRouter/productRouter.js
Client/src/components/CustomDataGrid/CustomDataGrid.component.jsx
Client/src/components/ProductsTable/ProductsTable.component.jsx
Client/src/components/Support/Support.component.jsx
Client/src/helpers/supportValidateForm.js
Client/src/services/productServices.js

mejornado validaciones formulario de contacto soporte

mejornado validaciones formulario de contacto soporte

---

Client/src/App.jsx
Client/src/Hook/useCheckAuthData.jsx

creando alertas con sweet alert para la verificacion de sesión

creando alertas con sweet alert para la verificacion de sesión

---

Client/package-lock.json
Client/package.json
Client/src/components/GoogleMap/GoogleMap.component.jsx

mapa de google desde API

---

Client/src/components/SearchBar/SearchBar.component.jsx
Client/src/redux/slices/historySlice.js
Client/src/redux/store.js
Client/src/services/historyUserService.js

ahora si metanle pero todavia le falta

Search bar

---

Client/src/components/ProductsTable/ProductsTable.component.jsx

Tabla select

---

Client/src/components/ProductsTable/ProductsTable.component.jsx
Client/src/services/categoriesServices.js

solucion error del precio al actualizar categoria

solucion error del precio al actualizar categoria

---

Client/src/components/ProductsTable/ProductsTable.component.jsx

ordenamiento alfabetico marcas y categorias

ordenamiento alfabetico marcas y categorias

---

Api/src/handlers/accountHandlers/authHandler.js
Client/src/components/LoginModal/LoginModal.component.jsx
Client/src/helpers/userValidate.js
Client/src/services/authServices.js
Client/src/views/publics/ChangePassword/ChangePasword.view.jsx

Se agregaron las opciones para recuperar la contraseña.

Recuperacion de contraseña

---

Client/src/components/ServicesTable/ServicesTable.component.jsx

Select tabla services

---

Client/src/components/Products/Products.component.jsx
Client/src/components/SearchBar/SearchBar.component.jsx

arreglos search

---

Api/src/controllers/userControllers/userController.js
Client/src/App.jsx
Client/src/components/Error404/Error404.component.jsx
Client/src/components/ServicesTable/ServicesTable.component.jsx
Client/src/components/UsersTable/UsersTable.component.jsx
Client/src/helpers/pathRoute.js
Client/src/views/publics/Error404/Error404.view.jsx

Tabla usuarios y demas cositas

Tabla usuarios

---

Client/src/components/ServicesTable/ServicesTable.component.jsx

checkbox a tabla servicios

---

Client/src/components/UserPanel/UserPanel.component.jsx
Client/src/components/UsersTable/UsersTable.component.jsx

Select tabla usuarios

---

Client/src/components/ProductsTable/ProductsTable.component.jsx

algunos cambios más

---

Client/src/components/CustomDataGrid/CustomDataGrid.component.jsx
Client/src/components/ServicesTable/ServicesTable.component.jsx

mas cambios

---

Client/src/components/CustomDataGrid/CustomDataGrid.component.jsx
Client/src/components/ProductsTable/ProductsTable.component.jsx
Client/src/components/ServicesTable/ServicesTable.component.jsx
Client/src/components/UsersTable/UsersTable.component.jsx
Client/src/utils/objectsTexts.js

edicion texto preguntas frecuentes

edicion texto preguntas frecuentes

---

Client/src/components/ProductCard/ProductCard.component.jsx

pequeños cambios

---

Client/src/components/Detail/Detail.component.jsx
Client/src/components/ProductCard/ProductCard.component.jsx

Arreglo en condicionales de producto sin stock y x productos disponibles

Arreglo en condicionales

---

Client/src/components/Footer/Footer.component.jsx
Client/src/utils/objectsTexts.js

links a info footer

---

Client/src/components/HomeProducts/HomeProducts.component.jsx
Client/src/components/SafePurchase/SafePurchase.component.jsx

responsive a SafePurchase

---

Client/public/site.webmanifest

cambio color de fondo
